version: '3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: /home/inception/srcs/services/mariadb
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - inception
    restart: on-failure

  nginx:
    container_name: nginx
    image: nginx
    build: /home/inception/srcs/services/nginx
    ports:
      - 443:443
    volumes:
      - wp_volume:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception
    restart: on-failure

  wordpress:
    container_name: wordpress
    image: wordpress
    build: /home/inception/srcs/services/wordpress
    volumes:
      - wp_volume:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    restart: on-failure
    env_file:
      - .env

volumes:
  wp_volume:
    driver_opts:
      type: none
      o: bind
      device: /home/ljahn/data/wp_volume
  db_volume:
    driver_opts:
      type: none
      o: bind
      device: /home/ljahn/data/db_volume

networks:
  inception:
    name: inception
    driver: bridge
        
